services:
  python:
    build:
      context: .
      dockerfile: ./docker/torch/Dockerfile
      args:
        - UID=${USERID:-1000}

    volumes:
      - .:/usr/src
    shm_size: '8gb'
    working_dir: /usr/src

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['0']

  install:
    build:
      context: .
      dockerfile: ./docker/install/Dockerfile
      args:
        - UID=${USERID:-1000}

    volumes:
      - .:/usr/src
    shm_size: '8gb'
    working_dir: /usr/src
    entrypoint: sh ./docker/install/entrypoint.sh

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['0']
